name: Publish as npm module
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: "16.x"
          registry-url: https://registry.npmjs.org/

      - name: Install AJV-CLI
        run: npm install -g ajv-cli

      - name: Build
        run: |
          npm ci
          npm run build

      - name: Publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_SECRET}}
